services:
  - type: web
    name: bioflow
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    healthCheckPath: /info
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
